branch: master
plugins:
  - @semantic-release/release-notes-generator
  - @semantic-release/npm
  - @semantic-release/github
  - - @semantic-release/git
    - message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
